INSERT INTO comands VALUES
(test(), 'RevolDance', 0, 0, 'Amateur Kids', 1),
(test(), 'Boys band', 0, 0, 'Amateur Kids', 2),
(test(), 'SHYK DANCE STUDIO', 0, 0, 'Amateur Kids', 3),
(test(), 'Yummy crew', 0, 0, 'Amateur Kids', 4),
(test(), 'Живчик (Jivchiki)', 0, 0, 'Amateur Kids', 5),
(test(), 'Energy Kids', 0, 0, 'Amateur Kids', 6),
(test(), 'DSL Crew Dance Studio Luna', 0, 0, 'Amateur Kids', 7),
(test(), 'BONDДіти', 0, 0, 'Amateur Kids', 8),
(test(), 'Voronins Studio', 0, 0, 'Amateur Kids', 9),
(test(), 'Explosion Kids', 0, 0, 'Amateur Kids', 10),
(test(), 'Sharm-S Dolls', 0, 0, 'Amateur Kids', 11),
(test(), 'Flash Mob Dance Studio Luna', 0, 0, 'Amateur Kids', 12),
(test(), 'Грация (Gratsiya)', 0, 0, 'Amateur Kids', 13),
(test(), 'Блиц (Blitz)', 0, 0, 'Amateur Kids', 14),
(test(), 'ЦЕХ (TSEH)', 0, 0, 'Amateur Kids', 15),
(test(), 'Cartoon Kids', 0, 0, 'Amateur Kids', 16),
(test(), 'LetS go Kids', 0, 0, 'Amateur Kids', 17),
(test(), 'ART FUSION LITTLE MONSTERS', 0, 0, 'Amateur Kids', 18),
(test(), 'Dance Family Spirit', 0, 0, 'Amateur Kids', 19);

INSERT INTO comands VALUES
(test(), 'Cтранность Dance studio Luna', 0, 0, 'Amateur Juniors', 20),
(test(), 'NoName dance studio', 0, 0, 'Amateur Juniors', 21),
(test(), 'THE BOND', 0, 0, 'Amateur Juniors', 22),
(test(), 'LEADER DANCE', 0, 0, 'Amateur Juniors', 23),
(test(), 'Main Event Crew All Stars Dance Centre', 0, 0, 'Amateur Juniors', 24),
(test(), 'ART FUSION GANGSTA', 0, 0, 'Amateur Juniors', 25),
(test(), 'Жардин де ля Данс (Jardin De Lya Dance)', 0, 0, 'Amateur Juniors', 26),
(test(), 'Future movement crew', 0, 0, 'Amateur Juniors', 27),
(test(), 'Dream Team (MAX DANCE)', 0, 0, 'Amateur Juniors', 28),
(test(), 'Diva dance Crew', 0, 0, 'Amateur Juniors', 29),
(test(), 'CREW WAY', 0, 0, 'Amateur Juniors', 30),
(test(), 'Kings of Chaos', 0, 0, 'Amateur Juniors', 31),
(test(), 'DSL Crew ', 0, 0, 'Amateur Juniors', 32),
(test(), 'ART FUSION FAM', 0, 0, 'Amateur Juniors', 33),
(test(), 'Funky Fresh Crew (MAX DANCE)', 0, 0, 'Amateur Juniors', 34),
(test(), 'ANGELLAS CREW', 0, 0, 'Amateur Juniors', 35),
(test(), 'К.О.РАТ', 0, 0, 'Amateur Juniors', 36),
(test(), 'Z-Royal All Stars Dance Centre', 0, 0, 'Amateur Juniors', 37),
(test(), 'One Beat Crew (Maxdance)', 0, 0, 'Amateur Juniors', 38),
(test(), 'Грация (Gratsiya)', 0, 0, 'Amateur Juniors', 39),
(test(), 'Banana crew', 0, 0, 'Amateur Juniors', 40),
(test(), 'Yes banda', 0, 0, 'Amateur Juniors', 41),
(test(), 'Dance for life', 0, 0, 'Amateur Juniors', 42),
(test(), 'Flying Stars', 0, 0, 'Amateur Juniors', 43),
(test(), 'Студия танца "Go Up"', 0, 0, 'Amateur Juniors', 44),
(test(), 'Brighting crew All Stars Dance Centre', 0, 0, 'Amateur Juniors', 45),
(test(), 'Sup Team', 0, 0, 'Amateur Juniors', 46),
(test(), 'Princess', 0, 0, 'Amateur Juniors', 47),
(test(), 'Fresh Baking', 0, 0, 'Amateur Juniors', 48),
(test(), 'LetS go', 0, 0, 'Amateur Juniors', 49),
(test(), 'Lil Alphas', 0, 0, 'Amateur Juniors', 50),
(test(), 'Dance Family Spirit', 0, 0, 'Amateur Juniors', 51),
(test(), 'Soul Side', 0, 0, 'Amateur Juniors', 52),
(test(), 'Atom Dance Crew', 0, 0, 'Amateur Juniors', 53),
(test(), 'Soul flame', 0, 0, 'Amateur Juniors', 54);


INSERT INTO comands VALUES
(test(), 'DSN Community', 0, 0, 'Amateur Adults', 55),
(test(), 'Hallucinations UA21', 0, 0, 'Amateur Adults', 56),
(test(), 'Tagless', 0, 0, 'Amateur Adults', 57),
(test(), 'FDC fam', 0, 0, 'Amateur Adults', 58),
(test(), 'WAY UP CREW (MAX DANCE)', 0, 0, 'Amateur Adults', 59),
(test(), 'ARTPEOPLE CREW', 0, 0, 'Amateur Adults', 60),
(test(), 'All Stars Dance Centre команда Ice-D Crew', 0, 0, 'Amateur Adults', 61),
(test(), 'Coconut Union', 0, 0, 'Amateur Adults', 62),
(test(), 'TRIBUTE TEAM', 0, 0, 'Amateur Adults', 63),
(test(), 'Soul crew', 0, 0, 'Amateur Adults', 64),
(test(), 'A tale of the town', 0, 0, 'Amateur Adults', 65),
(test(), 'Blaze Up crew', 0, 0, 'Amateur Adults', 66),
(test(), 'All Stars Dance Centre команда Modern Madness', 0, 0, 'Amateur Adults', 67);

INSERT INTO comands VALUES
(test(), 'Juicyfruits', 0, 0, 'Pro Kids', 68),
(test(), 'DIVA Dance', 0, 0, 'Pro Kids', 69),
(test(), 'RDF', 0, 0, 'Pro Kids', 70),
(test(), 'Грация (Gratsiya)', 0, 0, 'Pro Kids', 71),
(test(), 'Freshies crew', 0, 0, 'Pro Kids', 72),
(test(), 'Step By Step Dance School', 0, 0, 'Pro Kids', 73),
(test(), 'Feel More Crew', 0, 0, 'Pro Kids', 74),
(test(), 'ТОРНАДО (Tornado)', 0, 0, 'Pro Kids', 75),
(test(), 'Apple kids', 0, 0, 'Pro Kids', 76);

INSERT INTO comands VALUES
(test(), 'Energy Team', 0, 0, 'Pro Juniors', 77),
(test(), 'lil D', 0, 0, 'Pro Juniors', 78),
(test(), 'Step Up Shturm', 0, 0, 'Pro Juniors', 79),
(test(), 'SDSN Crew', 0, 0, 'Pro Juniors', 80),
(test(), 'Explosion Team', 0, 0, 'Pro Juniors', 81),
(test(), 'SHYK DANCE SHOW', 0, 0, 'Pro Juniors', 82),
(test(), 'Tornado crew/ Storm Fam', 0, 0, 'Pro Juniors', 83),
(test(), 'Beat Crew All Stars Dance Centre', 0, 0, 'Pro Juniors', 84),
(test(), 'Dessert Team - Harlem', 0, 0, 'Pro Juniors', 85),
(test(), 'ЛИЧНОСТЬ crew (Lichnost crew)', 0, 0, 'Pro Juniors', 86),
(test(), 'LADY-X', 0, 0, 'Pro Juniors', 89),
(test(), 'Блиц (Blitz)', 0, 0, 'Pro Juniors', 90),
(test(), 'Evolution Dance Centre ', 0, 0, 'Pro Juniors', 91),
(test(), 'ТОРНАДО (Tornado)', 0, 0, 'Pro Juniors', 92);

INSERT INTO comands VALUES
(test(), 'D.side Fam', 0, 0, 'Pro Adults', 93),
(test(), 'Unity Crew All Stars Dance Centre', 0, 0, 'Pro Adults', 94),
(test(), 'Maasai Crew', 0, 0, 'Pro Adults', 95),
(test(), 'Will Child Crew', 0, 0, 'Pro Adults', 96),
(test(), 'ACTION CREW', 0, 0, 'Pro Adults', 97),
(test(), 'Fem Force Crew', 0, 0, 'Pro Adults', 98),
(test(), 'SLICE FAM', 0, 0, 'Pro Adults', 99),
(test(), 'Explosion Crew All Stars Dance Centre', 0, 0, 'Pro Adults', 100),
(test(), 'Bad girls crew - Harlem', 0, 0, 'Pro Adults', 101),
(test(), 'Dark Side', 0, 0, 'Pro Adults', 102),
(test(), 'Clouds Company (Allyans Dance School)', 0, 0, 'Pro Adults', 103),
(test(), 'Lord Fam', 0, 0, 'Pro Adults', 104),
(test(), 'ТОРНАДО (Tornado)', 0, 0, 'Pro Adults', 105),
(test(), 'RDF', 0, 0, 'Pro Adults', 106),
(test(), 'CREW UA 21', 0, 0, 'Pro Adults', 107);

INSERT INTO comands VALUES
(test(), 'Виктория Щудляк (Victoria Shudlyak)', 0, 0, 'Solo', 108),
(test(), 'Kevo', 0, 0, 'Solo', 109),
(test(), 'Velissa', 0, 0, 'Solo', 110),
(test(), 'Дарина (Darina)', 0, 0, 'Solo', 111),
(test(), 'Никита (Nikita)', 0, 0, 'Solo', 112),
(test(), 'Амаль Кадыров (Amal Kadirov)', 0, 0, 'Solo', 113),
(test(), 'Плосковицкий Олександр (Ploscovitski Oleksandr)', 0, 0, 'Solo', 114),
(test(), 'Мирзо (Mirzo)', 0, 0, 'Solo', 115),
(test(), 'Анастасия Тернавская (Anastasia Ternavskaya)', 0, 0, 'Solo', 116),
(test(), 'Оксана (Oksana)', 0, 0, 'Solo', 117),
(test(), 'Тимур Карпинский (Timur Karpinskiy)', 0, 0, 'Solo', 118),
(test(), 'Лопатина Даша (Lopatina Dasha)', 0, 0, 'Solo', 119),
(test(), 'Олександр (Oleksandr)', 0, 0, 'Solo', 120),
(test(), 'Mariia', 0, 0, 'Solo', 121),
(test(), 'Александра Раковец (Alexandr Rakovets)', 0, 0, 'Solo', 122),
(test(), 'Анна Лещина (Anna Leshina)', 0, 0, 'Solo', 123),
(test(), 'Вероника Николенко (Veronika Nikolaenko)', 0, 0, 'Solo', 124),
(test(), 'Виктория Щудляк (Victoria Shudlyak)', 0, 0, 'Solo', 125),
(test(), 'Karina Exolosion', 0, 0, 'Solo', 126),
(test(), 'Рефат Абдуллаев (Rafat Abdulaev)', 0, 0, 'Solo', 127),
(test(), 'Дарья Савинова (Darya Savinovna)', 0, 0, 'Solo', 128),
(test(), 'Милана Полякевич (Milana Polyakevich)', 0, 0, 'Solo', 129),
(test(), 'Валентина Броварная (Valentin Brovarnaya)', 0, 0, 'Solo', 130),
(test(), 'Станинець Іра (Staninets Ira)', 0, 0, 'Solo', 131),
(test(), 'Карина Ткаченко (Karina Tkachenko)', 0, 0, 'Solo', 132),
(test(), 'Дарья Кадыгроб (Darya Kadigrob)', 0, 0, 'Solo', 133),
(test(), 'Андрей (Andrey)', 0, 0, 'Solo', 134),
(test(), 'Заболотняя Алиса (Zabolotnya Alisa)', 0, 0, 'Solo', 135),
(test(), 'Олесь Пасечник (Oles Pasechnik)', 0, 0, 'Solo', 136),
(test(), 'Никита Миршовка (Nikita Mirshovka)', 0, 0, 'Solo', 137),
(test(), 'Тоня Терсенова (Tonya Tersenova)', 0, 0, 'Solo', 138),
(test(), 'Алексей Черняков (Aleksey Chernyakov)', 0, 0, 'Solo', 139),
(test(), 'Данила Ковтун (Den)', 0, 0, 'Solo', 140),
(test(), 'Богдан Гальченко (Bogdan Galchenko)', 0, 0, 'Solo', 141),
(test(), 'LeraBera', 0, 0, 'Solo', 142),
(test(), 'Евгений Игнатенко (Evgeniy Ignatenko)', 0, 0, 'Solo', 143),
(test(), 'Анета Кочиш (Aneta Kochish)', 0, 0, 'Solo', 144),
(test(), 'Андрющенко Артем (Andrushenko Artem)', 0, 0, 'Solo', 145),
(test(), 'Mary', 0, 0, 'Solo', 146),
(test(), 'Custom', 0, 0, 'Solo', 147),
(test(), 'Артур Карпинский (Artur Karpinskiy)', 0, 0, 'Solo', 148),
(test(), 'Колос Мария (Kolos Mariya)', 0, 0, 'Solo', 149),
(test(), 'PopCorn (Влад Гречка)', 0, 0, 'Solo', 150),
(test(), 'Маша Компаниец (Masha Kompaniets)', 0, 0, 'Solo', 151),
(test(), 'Евгений (Evgeniy)', 0, 0, 'Solo', 152),
(test(), 'Мария Парфёнова (Maria Parfenova)', 0, 0, 'Solo', 153),
(test(), 'Виктория Перикаш (Victoria Perikash)', 0, 0, 'Solo', 154),
(test(), 'Анастасия (Anastasia)', 0, 0, 'Solo', 155),
(test(), 'Mariella', 0, 0, 'Solo', 156),
(test(), 'Виктория Милько (Victoria Milco)', 0, 0, 'Solo', 157),
(test(), 'Sashunia', 0, 0, 'Solo', 158),
(test(), 'Шевченко Дарья (Shevchenko Darya)', 0, 0, 'Solo', 159);
