-- MySQL Script generated by MySQL Workbench
-- Tue Mar 13 17:32:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DarcMatter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DarcMatter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DarcMatter` DEFAULT CHARACTER SET utf8 ;
USE `DarcMatter` ;

-- -----------------------------------------------------
-- Table `DarcMatter`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DarcMatter`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `NEM` VARCHAR(60) NULL,
  `Medium` VARCHAR(50) NULL,
  `Twitter` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
